###
http://localhost:3100/users/

###
http://localhost:3100/users/login
Content-Type: application/json

    {
        "username": "a",
        "password": "a"
    }

###
http://localhost:3100/users/add
Content-Type: application/json

    {
        "name": "b1",
        "username": "b",
        "password": "b",
        "email": "b@b.b",
        "role": "b",
        "message": "b"
    }

